/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2015-04-23 20:38:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if lt IE 7]><html class=\"no-js lt-ie9 lt-ie8 lt-ie7\" lang=\"en\"> <![endif]-->\r\n");
      out.write("<!--[if (IE 7)&!(IEMobile)]><html class=\"no-js lt-ie9 lt-ie8\" lang=\"en\"><![endif]-->\r\n");
      out.write("<!--[if (IE 8)&!(IEMobile)]><html class=\"no-js lt-ie9\" lang=\"en\"><![endif]-->\r\n");
      out.write("<!--[if (IE 9)]><html class=\"no-js ie9\" lang=\"en\"><![endif]-->\r\n");
      out.write("<!--[if gt IE 8]><!--> <html lang=\"en-US\"> <!--<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<!-- Meta Tags -->\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("\r\n");
      out.write("<title>YoTube | Redefining YouTube</title>   \r\n");
      out.write("\r\n");
      out.write("<meta name=\"description\" content=\"Insert Your Site Description\" /> \r\n");
      out.write("\r\n");
      out.write("<!-- Mobile Specifics -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"HandheldFriendly\" content=\"true\"/>\r\n");
      out.write("<meta name=\"MobileOptimized\" content=\"320\"/>   \r\n");
      out.write("\r\n");
      out.write("<!-- Mobile Internet Explorer ClearType Technology -->\r\n");
      out.write("<!--[if IEMobile]>  <meta http-equiv=\"cleartype\" content=\"on\">  <![endif]-->\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link href=\"_include/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Main Style -->\r\n");
      out.write("<link href=\"_include/css/main.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Supersized -->\r\n");
      out.write("<link href=\"_include/css/supersized.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"_include/css/supersized.shutter.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- FancyBox -->\r\n");
      out.write("<link href=\"_include/css/fancybox/jquery.fancybox.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Font Icons -->\r\n");
      out.write("<link href=\"_include/css/fonts.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Shortcodes -->\r\n");
      out.write("<link href=\"_include/css/shortcodes.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Responsive -->\r\n");
      out.write("<link href=\"_include/css/bootstrap-responsive.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"_include/css/responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Supersized -->\r\n");
      out.write("<link href=\"_include/css/supersized.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"_include/css/supersized.shutter.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Google Font -->\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900' rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("<!-- Fav Icon -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"#\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"#\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"#\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"#\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"#\">\r\n");
      out.write("\r\n");
      out.write("<!-- Modernizr -->\r\n");
      out.write("<script src=\"_include/js/modernizr.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Analytics -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("  var _gaq = _gaq || [];\r\n");
      out.write("  _gaq.push(['_setAccount', 'Insert Your Code']);\r\n");
      out.write("  _gaq.push(['_trackPageview']);\r\n");
      out.write("\r\n");
      out.write("  (function() {\r\n");
      out.write("    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;\r\n");
      out.write("    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';\r\n");
      out.write("    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);\r\n");
      out.write("  })();     \r\n");
      out.write("</script>\r\n");
      out.write("<!-- End Analytics -->\r\n");
      out.write("<style>\r\n");
      out.write("::-webkit-scrollbar {\r\n");
      out.write("    width: 12px;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("::-webkit-scrollbar-track {\r\n");
      out.write("    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0); \r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("background-color:#D0D0D0 ;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("::-webkit-scrollbar-thumb {\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5); \r\n");
      out.write("background-color:#FF6666;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- This section is for Splash Screen -->\r\n");
      out.write("\r\n");
      out.write("<!-- End of Splash Screen -->\r\n");
      out.write("\r\n");
      out.write("<!-- Homepage Slider -->\r\n");
      out.write("\r\n");
      out.write("<!-- End Homepage Slider -->\r\n");
      out.write("\r\n");
      out.write("<!-- Header -->\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"sticky-nav\">\r\n");
      out.write("    \t<a id=\"mobile-nav\" class=\"menu-nav\" href=\"#menu-nav\"></a>\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"logo\">\r\n");
      out.write("\r\n");
      out.write("    \t</div>\r\n");
      out.write("        <nav id=\"menu\">\r\n");
      out.write("        \t<ul id=\"menu-nav\">\r\n");
      out.write("            \t<li class=\"current\"><a href=\"#\" onClick=\"window.location='/yotube/homepage.jsp'\">Home</a></li>\r\n");
      out.write("            \t<li><input type=\"text\" id=\"search\" style=\"height:25px;width:460px\"></input>\r\n");
      out.write("        \t\t<button onClick=\"searching()\" type=\"button\" class=\"btn btn-danger\" style=\"height:36px; width:100px; text-align:center; padding: 5px 5px 5px 5px; margin-bottom: 8.5px\">Ranking</button></li>\r\n");
      out.write("        \t\t<li><a href=\"#\" onClick=\"window.location='/yotube/recent'\">Frequent Users</a></li>\r\n");
      out.write("        \t\t<li><a href=\"#\" onClick=\"window.location='/yotube/frequent'\">Frequent Searches</a></li>\r\n");
      out.write("                <li><a href=\"#\" onClick=\"window.location='Login.jsp'\">Logout</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("<!-- End Header -->\r\n");
      out.write("\r\n");
      out.write("<!-- Our Work Section -->\r\n");
      out.write("<div id=\"work\" class=\"page\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("    \t<!-- Title Page -->\r\n");
      out.write("     \t  <div class=\"span12\" style=\"height:140px\">\r\n");
      out.write("                <div class=\"title-page\">\r\n");
      out.write("                   <h5 class=\"title\">YoTube</h5>\r\n");
      out.write("                   <!--  <h6 class=\"title-description\">A new way to search YouTube.</h6>--></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- End Title Page -->\r\n");
      out.write("        \r\n");
      out.write("        <!-- Portfolio Projects -->\r\n");
      out.write("\t\t\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        \t<div class=\"span3\">\r\n");
      out.write("            \t<!-- Filter -->\r\n");
      out.write("                <nav id=\"options\" class=\"work-nav\">\r\n");
      out.write("                <ul class=\"type-work\">Categories</ul>\r\n");
      out.write("                <ul id=\"filters\" class=\"option-set\" data-option-key=\"filter\" style=\"width: 250px; height: 700px; overflow: auto; border:2px\">\r\n");
      out.write("                    <!-- <ul id=\"filters\" class=\"option-set\" data-option-key=\"filter\"> -->\r\n");
      out.write("                        <li><a href=\"#filter\" data-option-value=\"*\" class=\"selected\">All results</a></li>\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("       \t\r\n");
      out.write("                        \r\n");
      out.write("                </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- End Filter -->\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"span9\">\r\n");
      out.write("            <h3> Search results for \"<span style=\"font-style: italic; color:red;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${query}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\"</h3>\r\n");
      out.write("            \t<div class=\"row\">\r\n");
      out.write("                \t<section id=\"projects\">\r\n");
      out.write("                    \t<ul id=\"thumbs\">\r\n");
      out.write("                        \t\t\t\t\r\n");
      out.write("                        \t<!-- Video Info -->\r\n");
      out.write("                        \t        \r\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </section>\r\n");
      out.write("                    \r\n");
      out.write("            \t</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Portfolio Projects -->\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- End Our Work Section -->\r\n");
      out.write("\r\n");
      out.write("<!-- Socialize -->\r\n");
      out.write("<div id=\"social-area\" class=\"page\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("    \t<div class=\"row\">\r\n");
      out.write("            <div class=\"span12\">\r\n");
      out.write("                <nav id=\"social\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"\" title=\"Follow Me on Twitter\" target=\"_blank\"><span class=\"font-icon-social-twitter\"></span></a></li>\r\n");
      out.write("                        <li><a href=\"\" title=\"Follow Me on Facebook\" target=\"_blank\"><span class=\"font-icon-social-facebook\"></span></a></li>\r\n");
      out.write("                        <li><a href=\"\" title=\"Follow Me on Google Plus\" target=\"_blank\"><span class=\"font-icon-social-google-plus\"></span></a></li>\r\n");
      out.write("                        <li><a href=\"\" title=\"Follow Me on LinkedIn\" target=\"_blank\"><span class=\"font-icon-social-linkedin\"></span></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- End Socialize -->\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer>\r\n");
      out.write("\t<p class=\"credits\">&copy;2015  <a href=\"\" title=\"\">made with lots of smile :) :)</a> by CodeGeeks<a href=\"\" title=\"\"></a></p>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- End Footer -->\r\n");
      out.write("\r\n");
      out.write("<!-- Back To Top -->\r\n");
      out.write("<a id=\"back-to-top\" href=\"#\">\r\n");
      out.write("\t<i class=\"font-icon-arrow-simple-up\"></i>\r\n");
      out.write("</a>\r\n");
      out.write("<!-- End Back to Top -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Js -->\r\n");
      out.write("<script>\r\n");
      out.write("function Search(query){\r\n");
      out.write("\twindow.location = '/yotube/searchpage?query='+query;\r\n");
      out.write("\tdocument.getElementById(\"search\").value=query;\r\n");
      out.write("}\r\n");
      out.write("function searching(){\r\n");
      out.write("\tvar query= document.getElementById(\"search\").value;\r\n");
      out.write("\twindow.location = '/yotube/searchpage?query='+query;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js\"></script> <!-- jQuery Core -->\r\n");
      out.write("<script src=\"_include/js/bootstrap.min.js\"></script> <!-- Bootstrap -->\r\n");
      out.write("<script src=\"_include/js/supersized.3.2.7.min.js\"></script> <!-- Slider -->\r\n");
      out.write("<script src=\"_include/js/waypoints.js\"></script> <!-- WayPoints -->\r\n");
      out.write("<script src=\"_include/js/waypoints-sticky.js\"></script> <!-- Waypoints for Header -->\r\n");
      out.write("<script src=\"_include/js/jquery.isotope.js\"></script> <!-- Isotope Filter -->\r\n");
      out.write("<script src=\"_include/js/jquery.fancybox.pack.js\"></script> <!-- Fancybox -->\r\n");
      out.write("<script src=\"_include/js/jquery.fancybox-media.js\"></script> <!-- Fancybox for Media -->\r\n");
      out.write("<script src=\"_include/js/jquery.tweet.js\"></script> <!-- Tweet -->\r\n");
      out.write("<script src=\"_include/js/plugins.js\"></script> <!-- Contains: jPreloader, jQuery Easing, jQuery ScrollTo, jQuery One Page Navi -->\r\n");
      out.write("<script src=\"_include/js/main.js\"></script> <!-- Default JS -->\r\n");
      out.write("<!-- End Js -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("    \t\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("    \t\t\t\t\t");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /home.jsp(156,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topics.size() eq 0}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("       \t\t\t\t\t\t<li>No results to display</li>\r\n");
        out.write("    \t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("    \t\t\t\t\t");
        if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("    \t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
    // /home.jsp(160,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("i");
    // /home.jsp(160,9) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setBegin(0);
    // /home.jsp(160,9) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topics.size()-1}", java.lang.Integer.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).intValue());
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    \t\t\t\t\t<li><a href=\"#filter\" data-option-value=\".design\" onClick=\"Search('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topics.get(i)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("')\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topics.get(i)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</a>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topicCategory.get(i)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</li>\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /home.jsp(179,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("i");
    // /home.jsp(179,8) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setBegin(0);
    // /home.jsp(179,8) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${videoInfo.size()-1}", java.lang.Integer.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).intValue());
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <li class=\"item-thumbs span3\">\r\n");
          out.write("                                <!-- Fancybox - Gallery Enabled - Title - Full Image -->\r\n");
          out.write("                                <a class=\"hover-wrap fancybox-media\" data-fancybox-group=\"video\" title=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${videoInfo.get(i).getTitle()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${videoInfo.get(i).getUrl()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\">\r\n");
          out.write("                                <span class=\"overlay-img\" style=\"text-align:center;color:white;font-weight: 150;font-size:20px;vertical-align: middle;\">\r\n");
          out.write("                                <ul>\r\n");
          out.write("                                </br>\r\n");
          out.write("                                <li>View % - ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${videoInfo.get(i).getViewpercent()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</li>\r\n");
          out.write("                                </br>\r\n");
          out.write("                                <li>Like/Views % - ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${videoInfo.get(i).getLikeviewCount()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</li>\r\n");
          out.write("                                </br>   \r\n");
          out.write("                                <li>Dislike/Like % - ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${videoInfo.get(i).getDislikelikeCount()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</li>\r\n");
          out.write("                    <!--        <li>Views - ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${videoInfo.get(i).getViewCount()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</li>\r\n");
          out.write("                                <li>Likes - ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${videoInfo.get(i).getLikeCount()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</li>\r\n");
          out.write("                                <li>Dislikes - ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${videoInfo.get(i).getDislikeCount()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</li>   \r\n");
          out.write("                                <li>Comments - ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${videoInfo.get(i).getCommentCount()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</li> -->\r\n");
          out.write("                                </ul>\r\n");
          out.write("                                </span></a>\r\n");
          out.write("                                <!-- Thumb Image and Description -->\r\n");
          out.write("                                <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${videoInfo.get(i).getThumbnail()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" alt=\"\">\r\n");
          out.write("                            </li>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }
}
