/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2015-04-23 16:23:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class homepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if lt IE 7]><html class=\"no-js lt-ie9 lt-ie8 lt-ie7\" lang=\"en\"> <![endif]-->\r\n");
      out.write("<!--[if (IE 7)&!(IEMobile)]><html class=\"no-js lt-ie9 lt-ie8\" lang=\"en\"><![endif]-->\r\n");
      out.write("<!--[if (IE 8)&!(IEMobile)]><html class=\"no-js lt-ie9\" lang=\"en\"><![endif]-->\r\n");
      out.write("<!--[if (IE 9)]><html class=\"no-js ie9\" lang=\"en\"><![endif]-->\r\n");
      out.write("<!--[if gt IE 8]><!--> <html lang=\"en-US\"> <!--<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<!-- Meta Tags -->\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("\r\n");
      out.write("<title>YoTube | Redefining YouTube</title>   \r\n");
      out.write("\r\n");
      out.write("<meta name=\"description\" content=\"Insert Your Site Description\" /> \r\n");
      out.write("\r\n");
      out.write("<!-- Mobile Specifics -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"HandheldFriendly\" content=\"true\"/>\r\n");
      out.write("<meta name=\"MobileOptimized\" content=\"320\"/>   \r\n");
      out.write("\r\n");
      out.write("<!-- Mobile Internet Explorer ClearType Technology -->\r\n");
      out.write("<!--[if IEMobile]>  <meta http-equiv=\"cleartype\" content=\"on\">  <![endif]-->\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link href=\"_include/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Main Style -->\r\n");
      out.write("<link href=\"_include/css/main.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Supersized -->\r\n");
      out.write("<link href=\"_include/css/supersized.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"_include/css/supersized.shutter.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- FancyBox -->\r\n");
      out.write("<link href=\"_include/css/fancybox/jquery.fancybox.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Font Icons -->\r\n");
      out.write("<link href=\"_include/css/fonts.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Shortcodes -->\r\n");
      out.write("<link href=\"_include/css/shortcodes.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Responsive -->\r\n");
      out.write("<link href=\"_include/css/bootstrap-responsive.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"_include/css/responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Supersized -->\r\n");
      out.write("<link href=\"_include/css/supersized.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"_include/css/supersized.shutter.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Google Font -->\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900' rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("<!-- Fav Icon -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"#\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"#\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"#\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"#\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"#\">\r\n");
      out.write("\r\n");
      out.write("<!-- Modernizr -->\r\n");
      out.write("<script src=\"_include/js/modernizr.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Analytics -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("  var _gaq = _gaq || [];\r\n");
      out.write("  _gaq.push(['_setAccount', 'Insert Your Code']);\r\n");
      out.write("  _gaq.push(['_trackPageview']);\r\n");
      out.write("\r\n");
      out.write("  (function() {\r\n");
      out.write("    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;\r\n");
      out.write("    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';\r\n");
      out.write("    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);\r\n");
      out.write("  })();\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<!-- End Analytics -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- This section is for Splash Screen -->\r\n");
      out.write("\r\n");
      out.write("<!-- End of Splash Screen -->\r\n");
      out.write("\r\n");
      out.write("<!-- Homepage Slider -->\r\n");
      out.write("\r\n");
      out.write("<!-- End Homepage Slider -->\r\n");
      out.write("\r\n");
      out.write("<!-- Header -->\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"sticky-nav\">\r\n");
      out.write("    \t<a id=\"mobile-nav\" class=\"menu-nav\" href=\"#menu-nav\"></a>\r\n");
      out.write("        <div id=\"logo\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav id=\"menu\">\r\n");
      out.write("            <ul id=\"menu-nav\">\r\n");
      out.write("                <li class=\"current\"><a href=\"#\" onClick=\"window.location='/yotube/homepage.jsp'\">Home</a></li>\r\n");
      out.write("                <li><input type=\"text\" autofocus id=\"search\" style=\"height:25px;width:460px\"/>\r\n");
      out.write("                <button onClick=\"search()\" type=\"button\" class=\"btn btn-danger\" style=\"height:36px; width:100px; text-align:center; padding: 5px 5px 5px 5px; margin-bottom: 8.5px\" >Ranking</button></li>\r\n");
      out.write("                <li><a href=\"#\" onClick=\"window.location='/yotube/recent'\">Frequent Users</a></li>\r\n");
      out.write("                <li><a href=\"#\" onClick=\"window.location='/yotube/frequent'\">Frequent searches</a></li>\r\n");
      out.write("                <li><a href=\"#\" onClick=\"window.location='Login.jsp'\">Logout</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("<!-- End Header -->\r\n");
      out.write("\r\n");
      out.write("<!-- Our Work Section -->\r\n");
      out.write("<div id=\"work\" class=\"homepage\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("           <h2>Welcome to YoTube :) </h2><br>\r\n");
      out.write("            <h4>A new way to seach YouTube by categories (ontological terms) there by enhancing your searching experience.</h4>\r\n");
      out.write("            <h5>Search results will be ranked according to <i style=\"color:red\">View%, Likes/View%, Dislike/Like%, CommentCount.</i></h5>\r\n");
      out.write("            \r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("    \t<!-- Title Page -->\r\n");
      out.write("        <!-- End Title Page -->\r\n");
      out.write("        <!-- Portfolio Projects -->\r\n");
      out.write("\t\t\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("<!-- Socialize -->\r\n");
      out.write("<div id=\"social-area\" class=\"page\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("    \t<div class=\"row\">\r\n");
      out.write("            <div class=\"span12\">\r\n");
      out.write("                <nav id=\"social\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"\" title=\"Follow Me on Twitter\" target=\"_blank\"><span class=\"font-icon-social-twitter\"></span></a></li>\r\n");
      out.write("                        <li><a href=\"\" title=\"Follow Me on Facebook\" target=\"_blank\"><span class=\"font-icon-social-facebook\"></span></a></li>\r\n");
      out.write("                        <li><a href=\"\" title=\"Follow Me on Google Plus\" target=\"_blank\"><span class=\"font-icon-social-google-plus\"></span></a></li>\r\n");
      out.write("                        <li><a href=\"\" title=\"Follow Me on LinkedIn\" target=\"_blank\"><span class=\"font-icon-social-linkedin\"></span></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- End Socialize -->\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer>\r\n");
      out.write("\t<p class=\"credits\">&copy;2015  <a href=\"\" title=\"\">YoTub made your life simpler</a> by Team India<a href=\"\" title=\"\"></a></p>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- End Footer -->\r\n");
      out.write("\r\n");
      out.write("<!-- Back To Top -->\r\n");
      out.write("<a id=\"back-to-top\" href=\"#\">\r\n");
      out.write("\t<i class=\"font-icon-arrow-simple-up\"></i>\r\n");
      out.write("</a>\r\n");
      out.write("<!-- End Back to Top -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Js -->\r\n");
      out.write("<script>\r\n");
      out.write("function search(){\r\n");
      out.write("\tvar query= document.getElementById(\"search\").value;\r\n");
      out.write("\twindow.location = '/yotube/searchpage?query='+query;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js\"></script> <!-- jQuery Core -->\r\n");
      out.write("<script src=\"_include/js/bootstrap.min.js\"></script> <!-- Bootstrap -->\r\n");
      out.write("<script src=\"_include/js/supersized.3.2.7.min.js\"></script> <!-- Slider -->\r\n");
      out.write("<script src=\"_include/js/waypoints.js\"></script> <!-- WayPoints -->\r\n");
      out.write("<script src=\"_include/js/waypoints-sticky.js\"></script> <!-- Waypoints for Header -->\r\n");
      out.write("<script src=\"_include/js/jquery.isotope.js\"></script> <!-- Isotope Filter -->\r\n");
      out.write("<script src=\"_include/js/jquery.fancybox.pack.js\"></script> <!-- Fancybox -->\r\n");
      out.write("<script src=\"_include/js/jquery.fancybox-media.js\"></script> <!-- Fancybox for Media -->\r\n");
      out.write("<script src=\"_include/js/jquery.tweet.js\"></script> <!-- Tweet -->\r\n");
      out.write("<script src=\"_include/js/plugins.js\"></script> <!-- Contains: jPreloader, jQuery Easing, jQuery ScrollTo, jQuery One Page Navi -->\r\n");
      out.write("<script src=\"_include/js/main.js\"></script> <!-- Default JS -->\r\n");
      out.write("<!-- End Js -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
